   _____  _______      __  _____                            _            
  / ____|/ ____\ \    / / |_   _|                          | |           
 | |    | (___  \ \  / /    | |  _ __ ___  _ __   ___  _ __| |_ ___ _ __ 
 | |     \___ \  \ \/ /     | | | '_ ` _ \| '_ \ / _ \| '__| __/ _ \ '__|
 | |____ ____) |  \  /     _| |_| | | | | | |_) | (_) | |  | ||  __/ |   
  \_____|_____/    \/     |_____|_| |_| |_| .__/ \___/|_|   \__\___|_|   
                                          | |                         
                                          |_|

Connected, dropping old data for store 99
connected to database
importing data... please wait...
Traceback (most recent call last):
  File "/Users/Shared/RemoteShare/inventory/admin/csvImporter.py", line 163, in <module>
    copyfile(filepath, "oldStoreFiles/Store"+storeNum+".csv")
  File "/usr/local/Cellar/python@3.9/3.9.1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: 'oldStoreFiles/Store99.csv'
